# Generated by Django 5.0.6 on 2024-09-25 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='analyzed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='tumor_detected',
            field=models.BooleanField(),
        ),
    ]
