# Generated by Django 5.1.7 on 2025-04-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri_analysis', '0003_analysisresult_segmented_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='bounded_box_image',
            field=models.ImageField(blank=True, null=True, upload_to='bounded_boxes/'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='tumor_size_mm2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='tumor_size_px',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
