# Generated by Django 5.1.7 on 2025-04-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri_analysis', '0004_analysisresult_bounded_box_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='crp_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='edema_volume_ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='headache_frequency_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='ki67_index_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='ldh_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='stage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='symptom_duration_months',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='tumor_size_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='bounded_box_image',
            field=models.ImageField(blank=True, null=True, upload_to='with_bounding_box/'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='segmented_result',
            field=models.ImageField(blank=True, null=True, upload_to='tumor_mask/'),
        ),
    ]
