# Generated by Django 5.1.7 on 2025-04-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri_analysis', '0005_analysisresult_age_analysisresult_crp_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('doctor_reg_number', models.CharField(max_length=50)),
                ('unique_id', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
    ]
