# Generated by Django 5.1.7 on 2025-04-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mri_analysis', '0006_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='unique_id',
        ),
    ]
