# Generated by Django 5.1.7 on 2025-04-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri_analysis', '0007_remove_doctor_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='bounded_box_image',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='segmented_result',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='bounded_box_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='original_mri_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='segmented_result_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
